name: Create Release

on:
  - push
  - workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.create_release.outputs.release_tag }}
    steps:
    - uses: actions/checkout@v3
    - name: Create Release
      id: create_release
      run: |
        release_tag="$(uuidgen)"
        echo "release_tag=${release_tag}" >> "${GITHUB_OUTPUT}"
        gh release create "${release_tag}" --draft --target "${GITHUB_SHA}"

  build:
    needs: create_release
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu24.04, ubuntu22.04, ubuntu20.04]
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v3
    - name: Build Release
      id: build_release
      run: |
        DEVELOPER_DIR=/Applications/Xcode_15.4.app/Contents/Developer ./create-toolchain ${{ matrix.os }}

    - name: Attach Build To Release
      run: |
        set -x
        gh release upload ${{ needs.create_release.outputs.release_tag }} packages/*-${{ matrix.os }}.tar.xz
